### ISSUE TITLE
Not working for class file versions 52.0

### ISSUE THREAD

**Issue by itsmrajesh** [Majlanky/couch-slacker#21]
2.0.0 is not compatible with the class file version of 52.0

**Comment by Majlanky** [comment]
Hello Rajesh and thank you very much for the issue. We really appreciated it. 👏 
Can you tell us, why you need the compatibility with JDK8? Do not get us wrong, we respect the need, but we want to know if there is a proper reason that redeems the eventual effort. 🤔 
PS: if there is anybody who wants the compatibility, lets +1, please 🙏

**Comment by itsmrajesh** [comment]
Because JDK8 is what I'm using for most of my projects.
There is no other reason for JDK8 and it is also the minimum version that spring boot is supporting.
It would be helpful if the library is supporting starting from JDK8.

**Comment by Majlanky** [comment]
> Because JDK8 is what I'm using for most of my projects.
> There is no other reason for JDK8 and it is also the minimum version that spring boot is supporting.
> It would be helpful if the library is supporting starting from JDK8.

Makes sense... Thank you for your reply. We are going to fix it in the current milestone

**Comment by Majlanky** [comment]
Solved in 64fa16404e923e8a12492dc3a66256597506076a
