### ISSUE TITLE
Unable to build using Basic Access API per documentation

### ISSUE THREAD

**Issue by ShubhamShah** [Majlanky/couch-slacker#48]
As per documentation, its says for basic access
`CouchDbProperties properties = new CouchDbProperties("http://localhost:5984/", "admin", "password");
CouchDbClient client = CouchDbClient.builder().properties(properties).build();
`
But when used, giving runtime error 
`
java.lang.IllegalArgumentException: CouchDbContext must be set to build client up`

![image](https://user-images.githubusercontent.com/6258965/138222424-ca61c512-0289-46b6-8400-09fb3dc2c208.png)

**Comment by Majlanky** [comment]
Everything should be working now for simple approach. @ShubhamShah I am planning to do demo repo but right now I am overwhelmed by work. I will try to do it ASAP. Let me know, if you hit another issues for simple use.
